name: ns_lms_os_sdk
description: A professional, open-source Flutter SDK by NavaSanganakah Multiventures to seamlessly connect any Flutter application with the Cloudflare-backed LMS server.
version: 0.0.1
homepage: https://github.com/navasanganakah/ns_lms_os_sdk
issue_tracker: https://github.com/navasanganakah/ns_lms_os_sdk/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
