name: Publish ns_lms_os_sdk to pub.dev

on:
  workflow_dispatch: # Manual trigger for publishing

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC authentication with pub.dev
      contents: read
    defaults:
      run:
        working-directory: ./ns_lms_os_sdk
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Format Code
        run: dart format --set-exit-if-changed .

      - name: Analyze Code
        run: flutter analyze

      - name: Publish Package to pub.dev
        uses: dart-lang/setup-dart/publish@v1
        with:
          workingDirectory: ./ns_lms_os_sdk
